### ISSUE TITLE
Sollte gehen

### ISSUE THREAD

**Issue by DerTyp7214** [sebinside/PremiereAHK#4]
edit:
habs getestet, es geht
```js
const endpoint = function (router, path, command) {
router.get(path, function(req, res) {
    res.json({ message: 'ok.' });   
	csInterface.evalScript(command + "()");
    });
}
```
`endpoint(router, '/test', 'lol');`

**Comment by MTRNord** [comment]
Geht das nicht erst ab ES2016? (hab keine ahnung von premiere scripts und ob das ES2016 kann xD aber in den meisten browsern geht das so nicht von grund auf)

**Comment by DerTyp7214** [comment]
> Geht das nicht erst ab ES2016? (hab keine ahnung von premiere scripts und ob das ES2016 kann xD aber in den meisten browsern geht das so nicht von grund auf)

zur not muss man halt `function (router, path, command) {...` schreiben
